使用NumPy完成以下各題程式碼，上傳ipynbfile。
1.建立一個由10個整數0組成的陣列。
2.建立一個由10個整數1組成的陣列。
3.建立一個由10個整數5組成的陣列。
4.建立一個由10至50所有整數組成的陣列。
5.建立一個由10至50所有偶數組成的陣列。
6.如何產生以下陣列: 
7.建立一個3*3的單位矩陣。
8.建立一個陣列，由1個介於0至1間的隨機數字組成。
9.建立一個陣列，由25個來自標準常態分佈的隨機數字組成。

In [1]:
import numpy as np
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
np.repeat(5,10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [9]:
arr = np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [16]:
np.random.rand(1)

array([0.80433325])

In [17]:
np.random.randn(5,5)

array([[ 0.10054443,  0.78736456,  1.23214772, -0.63362963,  1.49939881],
       [ 0.99200896, -0.74719962, -0.71978702, -1.29106608, -1.78094581],
       [ 0.60129964,  1.03585427, -0.25965252, -0.48037904, -0.35968466],
       [ 0.75974866, -0.77500073,  0.72179204, -0.05288059,  1.1704921 ],
       [-0.24144186, -2.18691975, -1.46307779, -1.087586  , -1.35935119]])