In [1]:
import numpy as np 

In [5]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.repeat(5,10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [18]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [20]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [25]:
arr = np.arange(9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [142]:
#np.random.rand(1)
np.random.random_sample()

0.22042244227908647

In [156]:
np.random.randn(25)

array([-2.26842038,  2.61807796,  0.42319399,  1.6693523 , -1.67851067,
        0.54120421,  0.06394458,  1.97274997, -1.0533753 ,  0.8670346 ,
        0.46664967,  0.94933883,  0.53136497, -0.08182763, -0.31039125,
        0.18157325,  1.98805834, -0.18437833,  1.56995795,  1.03781799,
        0.4522123 , -1.31197111, -1.09937131,  0.54401733, -0.1512544 ])