Indexing & Selection

Indexing

In [1]:
import numpy as np

In [3]:
# Creating sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]
arr[-3]
arr[1:5]
#用法類似於list

array([1, 2, 3, 4])

In [8]:
arr[1:5] = 12 # replacing values in numpy array
arr

array([ 0, 12, 12, 12, 12,  5,  6,  7,  8,  9, 10])

切片後變更的陣列內容也會影響原本帳陣列

In [9]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

若要讓原本陣列不被影響，需使用arr.copy方法

In [13]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Indexing a 2D array (matrix)
The general format:
    arr_2d[row][col] or arr2d[row,col]

In [16]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
arr_2d[0] #顯示第一 row

array([ 5, 10, 15])

In [19]:
arr_2d[0][0] #顯示第一 row 的第一 column

5

In [20]:
arr_2d[0,0] #與上面相同

5

In [26]:
# shape (2,2) from top right corner  :2其實只到第1row跟for in range 一樣 只到 n-1
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

Indexing a 3D array (matirces)

In [28]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
# 第一層的第一row的index=1開始
arr3d[0][0][1:]

array([2, 3])

Fancy Indexing
One dimension 
Allowing to select entire rows or columns out of order

In [33]:
a = np.random.randint(1,100,8)
a

array([48, 72, 42, 89, 73, 35, 83, 52])

In [34]:
ind = [1,2,5]
a[ind]

array([72, 42, 35])

In [36]:
a[[1,2,5]]

array([72, 42, 35])

In [44]:
ind_1 = np.array([[1,2],[5,4]])
a[ind_1]
# 用此法可以產出跟原本形狀不同的陣列、矩陣

array([[72, 42],
       [35, 73]])

In [43]:
arr_2d[[0,2]]
# 2維為選擇該列 (第1列，第3列)

array([[ 5, 10, 15],
       [35, 40, 45]])

Two dimensions

In [45]:
b = np.random.randint(1,10,12).reshape((3,4)) # .reshape 將原本一維陣列轉為 2 維
b

array([[8, 3, 2, 2],
       [4, 5, 3, 8],
       [2, 6, 9, 1]])

In [46]:
ro = np.array([0,1,2])
co = np.array([2,1,3])
b[ro,co]

# 1st value: b[0,2]
# 2nd value: b[1,1]
# 3rd value: b[2,3]

array([2, 5, 1])

In [47]:
b[::2,1::2] #最後一個冒號為間隔

array([[3, 2],
       [6, 1]])

In [53]:
arr6_6 = np.arange(0,36).reshape(6,6)
arr6_6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [56]:
arr6_6[:, 2]

array([ 2,  8, 14, 20, 26, 32])

In [57]:
arr6_6[2::2, ::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [59]:
arr6_6[0,3:5]

array([3, 4])

In [61]:
arr6_6[4:,4:]

array([[28, 29],
       [34, 35]])

In [62]:
arr_2d6 = np.arange(0,36).reshape(6,6)
arr_2d6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [63]:
arr_2d6[[0,1,2,3,4,5],[0,1,2,3,4,5]]

array([ 0,  7, 14, 21, 28, 35])

Selection

In [64]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [67]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [68]:
arr[bool_arr] #列出arr中 > 4 的數值

array([ 5,  6,  7,  8,  9, 10])

In [69]:
arr[(arr > 2)& (arr<8)]

array([3, 4, 5, 6, 7])

In [70]:
arr[(arr<2)|(arr>8)]

array([ 1,  9, 10])

In [71]:
arr_2d = np.random.randint(1,101,50).reshape(5,10)
arr_2d

array([[48, 26, 87, 48, 19, 13, 28, 29, 41, 60],
       [39, 47, 50, 15, 92, 48, 91, 19,  7, 41],
       [74, 30, 39,  2, 79, 28, 59, 41, 71, 17],
       [ 6, 87, 69, 67, 60, 34, 18, 16, 74, 32],
       [79, 31, 57, 94, 74, 27, 68, 94,  1, 74]])

In [74]:
arr_2d[1:3,3:5]

array([[15, 92],
       [ 2, 79]])

In [76]:
arr_2d[(arr_2d>30)&(arr_2d<46)]

array([41, 39, 41, 39, 41, 34, 32, 31])

Numpy Operations

In [79]:
arr = np.arange(0,15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
arr+arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [81]:
arr*arr

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [82]:
arr-arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [83]:
arr/arr
# Warning on division by zero, but not an error,jsut replaced with nan

C:\Users\bill1\AppData\Local\Temp\ipykernel_30436\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [84]:
1/arr
# Also warning, but not an error instead infinity

C:\Users\bill1\AppData\Local\Temp\ipykernel_30436\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111],
       [0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857]])

In [85]:
arr**3

array([[   0,    1,    8,   27,   64],
       [ 125,  216,  343,  512,  729],
       [1000, 1331, 1728, 2197, 2744]], dtype=int32)

In [86]:
arr+100

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114]])

In [87]:
arr%2

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]], dtype=int32)

Universal Array Functions

In [89]:
np.sqrt(arr)
# Taking Square Roots
#arr.sqrt() 不能這樣寫

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [90]:
np.exp(arr)
#Calculating exponential(e^)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06]])

In [92]:
np.max(arr)
arr.max() #兩種寫法都可以

14

In [93]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736]])

In [94]:
np.log(arr) # e 為底 ln

C:\Users\bill1\AppData\Local\Temp\ipykernel_30436\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733]])

In [ ]:
np.log2(arr) # 2 為底 log

In [95]:
arr = np.arange(9).reshape((3,3))
arr.T # 轉置矩陣

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [98]:
print(arr.dot(arr.T)) #轉置矩陣與原來矩陣內積
print(np.dot(arr,arr.T))
print(arr @ arr.T)

#三種寫法都可以

[[  5  14  23]
 [ 14  50  86]
 [ 23  86 149]]
[[  5  14  23]
 [ 14  50  86]
 [ 23  86 149]]
[[  5  14  23]
 [ 14  50  86]
 [ 23  86 149]]


Mathametics method

In [99]:
arr = np .arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [102]:
print(arr.sum()) #所有元素加總
print(arr.sum(0)) #行加總
print(arr.sum(1)) #列加總

15
[3 5 7]
[ 3 12]


In [106]:
print(arr)
print(arr.mean()) #全部元素的平均
print(arr.mean(0)) #行平均 
print(arr.mean(1)) #列平均

[[0 1 2]
 [3 4 5]]
2.5
[1.5 2.5 3.5]
[1. 4.]


In [109]:
arr.std() #全部元素標準差
arr.std(0) #行標準差
arr.std(1) #列標準差

array([1.5, 1.5, 1.5])

In [121]:
arr = np.random.randint(0,101,15).reshape(3,5)
print(arr)
print((arr>50)&(arr<80))
print(arr[(arr>50)&(arr<80)]) #下條件後要印出符合條件之數字需用arr[]包起來
print(arr[(arr>50)&(arr<80)].sum()) #可以再加上數學與運算
print(arr[(arr>50)&(arr<80)].mean())
print(arr[(arr>50)&(arr<80)].std())

[[25 75 14 37 21]
 [42 90 21 67 82]
 [30  4 29 15 14]]
[[False  True False False False]
 [False False False  True False]
 [False False False False False]]
[75 67]
142
71.0
4.0
