Numpy Array speed vs Python List

In [3]:
import numpy as np
my_arr = np.arange(100000000)
my_list = list(range(100000000))

%time for _ in range(10): my_arr2 = my_arr*2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 766 ms
Wall time: 767 ms
CPU times: total: 42.2 s
Wall time: 42.2 s


np.array 可以將 list 直接轉乘 array

In [7]:
my_list = [1,2,3]
my_list2 = [[[1,2],[2,3]],[[4,5],[5,6]]]
arr = np.array(my_list)
arr2 = np.array(my_list2)
print(arr)
print(arr2)

[1 2 3]
[[[1 2]
  [2 3]]

 [[4 5]
  [5 6]]]


In [8]:
print(type(arr))
print(arr.ndim) # Number of array dimensions
print(arr.shape) # Current shape of an array
print(type(arr2))
print(arr2.ndim)
print(arr2.shape)

<class 'numpy.ndarray'>
1
(3,)
<class 'numpy.ndarray'>
3
(2, 2, 2)


Built-in Methods

np.arange is an array-valued version of the built-in Python range function

In [11]:
arr = np.arange(3) 
print(arr)
print(arr.ndim)
print(arr.shape)

[0 1 2]
1
(3,)


In [12]:
np.arange(3.0)

array([0., 1., 2.])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.zeros() generates arrays of zeros

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [20]:
print(np.zeros((1,5)))
print(np.zeros((1,5)).ndim)

[[0. 0. 0. 0. 0.]]
2


In [21]:
np.zeros((5,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

np.ones() generates array of ones
用法與 np.zeros 相同

In [22]:
np.ones(3)

array([1., 1., 1.])

np.linspace() 可以生成含浮點數之 array，np.arange()生成之數列有浮點數時精度可能會損失
語法:
arr = np.linspace(start, end, num=numpoints)

endpoint 關鍵字參數
預設為 Ture -> 會包含 end 之數字
arr = np.linspace(start,end,num,endpoint=False) 則不包含

retstep 
arr = np.linspace(start,end,num,retstep=True)
會返回數字間格及array

axis
預設為 0 -> 若為2*3
arr = np.linspace(start,end,num,axis=1)
會變成3*2

In [24]:
np.linspace(1,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [27]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [29]:
np.linspace(1,10,100,endpoint=False)

array([1.  , 1.09, 1.18, 1.27, 1.36, 1.45, 1.54, 1.63, 1.72, 1.81, 1.9 ,
       1.99, 2.08, 2.17, 2.26, 2.35, 2.44, 2.53, 2.62, 2.71, 2.8 , 2.89,
       2.98, 3.07, 3.16, 3.25, 3.34, 3.43, 3.52, 3.61, 3.7 , 3.79, 3.88,
       3.97, 4.06, 4.15, 4.24, 4.33, 4.42, 4.51, 4.6 , 4.69, 4.78, 4.87,
       4.96, 5.05, 5.14, 5.23, 5.32, 5.41, 5.5 , 5.59, 5.68, 5.77, 5.86,
       5.95, 6.04, 6.13, 6.22, 6.31, 6.4 , 6.49, 6.58, 6.67, 6.76, 6.85,
       6.94, 7.03, 7.12, 7.21, 7.3 , 7.39, 7.48, 7.57, 7.66, 7.75, 7.84,
       7.93, 8.02, 8.11, 8.2 , 8.29, 8.38, 8.47, 8.56, 8.65, 8.74, 8.83,
       8.92, 9.01, 9.1 , 9.19, 9.28, 9.37, 9.46, 9.55, 9.64, 9.73, 9.82,
       9.91])

In [30]:
np.linspace(1,10,100,endpoint=False,retstep=True)

(array([1.  , 1.09, 1.18, 1.27, 1.36, 1.45, 1.54, 1.63, 1.72, 1.81, 1.9 ,
        1.99, 2.08, 2.17, 2.26, 2.35, 2.44, 2.53, 2.62, 2.71, 2.8 , 2.89,
        2.98, 3.07, 3.16, 3.25, 3.34, 3.43, 3.52, 3.61, 3.7 , 3.79, 3.88,
        3.97, 4.06, 4.15, 4.24, 4.33, 4.42, 4.51, 4.6 , 4.69, 4.78, 4.87,
        4.96, 5.05, 5.14, 5.23, 5.32, 5.41, 5.5 , 5.59, 5.68, 5.77, 5.86,
        5.95, 6.04, 6.13, 6.22, 6.31, 6.4 , 6.49, 6.58, 6.67, 6.76, 6.85,
        6.94, 7.03, 7.12, 7.21, 7.3 , 7.39, 7.48, 7.57, 7.66, 7.75, 7.84,
        7.93, 8.02, 8.11, 8.2 , 8.29, 8.38, 8.47, 8.56, 8.65, 8.74, 8.83,
        8.92, 9.01, 9.1 , 9.19, 9.28, 9.37, 9.46, 9.55, 9.64, 9.73, 9.82,
        9.91]),
 0.09)

np.eye
Creates an identity matrix(單位矩陣)
numpy.eye(N, M=None, k=0, dtype=<class 'flost'>,order='C')

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.eye(4,M=6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [40]:
np.eye(4,M=6,k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

Random

rand 會在0~1之間隨機產生指定個數之數字

In [41]:
np.random.rand(3)

array([0.24820069, 0.11181946, 0.06816046])

In [43]:
np.random.rand(5,5)

array([[0.74985486, 0.54865074, 0.37811064, 0.88110548, 0.41098858],
       [0.52292172, 0.6971175 , 0.42856522, 0.05069205, 0.94131737],
       [0.48201489, 0.93270666, 0.75469456, 0.96165504, 0.88800865],
       [0.12487626, 0.50592859, 0.24398713, 0.03562302, 0.40439127],
       [0.46042792, 0.35628782, 0.26592813, 0.22130768, 0.72920492]])

randn 回傳常態分佈下指定個數之數字

In [44]:
np.random.randn(2)

array([0.90635552, 1.34521103])

In [45]:
np.random.randn(5,5)

array([[-0.79309283, -0.72456223,  0.2565965 ,  1.39422955,  0.48939811],
       [-0.8596733 , -1.22590223, -1.47022512, -0.68365394, -0.36414011],
       [ 1.51494978,  0.61430753,  0.69083549,  0.54473427, -0.1550176 ],
       [ 0.11146364, -0.79735483,  0.89535735, -1.01159385,  0.25717476],
       [ 0.92802579,  1.99183679, -1.39234652, -1.49886946, -2.39160633]])

randint 回傳指定個數指定區間數字(昇冪) (未指定個數則回傳一個)

In [47]:
np.random.randint(1,10)

7

In [46]:
np.random.randint(1,10,5)

array([1, 6, 1, 3, 4])

In [48]:
np.random.randint(1,10,(2,4)) # return a 2 * 4 array

array([[2, 8, 9, 1],
       [4, 2, 4, 9]])

Array Attributes and Methods

In [52]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,20)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 9 45 48 40 37 20  4 47 48 11 16 42 16 23 18 17 18  3 28 16]


In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
ranarr.reshape(5,4)

array([[ 9, 45, 48, 40],
       [37, 20,  4, 47],
       [48, 11, 16, 42],
       [16, 23, 18, 17],
       [18,  3, 28, 16]])

max
min
argmax 將陣列展平後回傳最大值的 index
argmin 將陣列展平後回傳最小值的 index

In [56]:
ranarr.reshape(5,4).max()

48

In [57]:
ranarr.reshape(5,4).argmax()

2

In [58]:
ranarr.reshape(5,4).argmax(axis=1) #返回每一行最大值之index

array([2, 3, 0, 1, 2], dtype=int64)

In [ ]:
ranarr.reshape(5,4).argmax(axis=0) #返回每一列最大值之index

shape
Shape is an attribute that arrays have (not a method)

In [59]:
arr = np.arange(25)
arr.shape

(25,)

In [60]:
arr.reshape(1,25).shape  #前面參數為 row , 後面為 column

(1, 25)

In [62]:
arr.reshape(25,1).shape

(25, 1)

dtype
data type

In [63]:
arr.dtype

dtype('int32')

In [64]:
w = np.array(['A','B'])
x = np.array([1,2])
y = np.array([1.0,2.0])  # Let numpy choose the datatype
z = np.array([1,2],dtype=np.int64)  # Force a particular datatype
print(w.dtype)
print(x.dtype)
print(y.dtype)
print(z.dtype)

<U1
int32
float64
int64
